### ISSUE TITLE
gminer2.59 not worker for 6800xt

### ISSUE THREAD

**Issue by loftgame** [develsoftware/GMinerRelease#303]
the log output. OpenCL initialization failed

**Comment by filipesarturi** [comment]
me too on 6800

**Comment by HackerZeus** [comment]
Seems fixed now

**Comment by LukeTurvey** [comment]
This error still occur for me on v2.74.

I am using a 6800XT.

I see in the log:
AMD Driver: Unknown
Failed to initialize miner on GPU0: AMD Radeon RX 6800 XT 16GB [0000:06:00.0]: OpenCL initialization failed
No devices for mining

rocminfo and clinfo both can see my card...

Notably mining works for me when using TeamRedMiner the GPU is fine, it can initialize OpenCL, so it seems this is a bug specific to GMiner. It's too bad as I would really like to try GMiner! 😔
